# Generated by Django 4.2 on 2023-07-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=50)),
                ('prev_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('today_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('today_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prev_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('today_volume', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
