# Generated by Django 4.2 on 2023-07-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_watchlist_symbol_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='change_percent',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='change_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='prev_close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='prev_high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='today_high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='today_low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='today_volume',
            field=models.CharField(max_length=100),
        ),
    ]
