# Generated by Django 4.2 on 2023-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_watchlist_change_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border_FetchedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
