# Generated by Django 4.2 on 2023-07-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_border_fetcheddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_stock_underlying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
