# Generated by Django 4.2 on 2023-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_volumegainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostActiveStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField()),
            ],
        ),
    ]
